name: Reformato
on:
  workflow_dispatch: #Esto nos permite ejecutar el workflow desde el menu actions de github.

jobs:
  reformat:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v3             
        with:                                                
          args: "--skip-sorting-imports --replace"  
          github-token: ${{ secrets.GITHUB_TOKEN }}
