name: Pruebas de Integracion

on:
  workflow_dispatch: # Esto nos permite ejecutar el workflow desde el menú Actions de GitHub.
  push:              # Ejecuta el workflow cuando se hace un push en la branch main.
    branches:
      - main
      - dev
  pull_request:      # Ejecuta el workflow cuando se hace un pull request de la branch main.
    branches:
      - main
      - dev

jobs:
  checkformat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código fuente
        uses: actions/checkout@v3

      - name: Verificar formato de código
        uses: axel-op/googlejavaformat-action@v3
        with:
          skip-commit: true
          
  utesting:
    runs-on: ubuntu-latest
    steps:
    - name: Copiar código
      uses: actions/checkout@v2

    - name: Preparar JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compilar código
      run: javac -cp .:lib/* JavaTestIntegracion.java

    - name: Ejecutar las pruebas
      run: java -cp .:lib/* org.junit.runner.JUnitCore JavaTestIntegracion

  checkstyle:
    runs-on: ubuntu-latest
    steps:
    - name: Copiar código
      uses: actions/checkout@v2

    - name: Preparar JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Ejecutar Checkstyle
      run: |
        chmod +x ./checkstyle/run_checkstyle.sh
        ./checkstyle/run_checkstyle.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copiar código
        uses: actions/checkout@v2

      - name: Preparar JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar código
        run: javac -cp .:lib/* Main.java

      - name: Ejecutar código
        run: java -cp .:lib/* Main
